blog/urls.py
from posixpath import basename
from django.urls import path
from rest_framework import routers

from . import views
from . import views_api

app_name = "blog"

urlpatterns = [
    path("", views.BlogListView.as_view(), name="blogs"),
    path("blog/new/", views.BlogCreateView.as_view(), name="blog-create"),
    path("blog/<slug:slug_value>/", views.BlogDetailView.as_view(), name="blog-detail"),
    path("blog/<slug:slug_value>/edit/", views.BlogUpdateView.as_view(), name="blog-update"),
    path(
        "blog/<slug:slug_value>/new/",
        views.PostCreateView.as_view(),
        name="post-create",
    ),
    path("post/<slug:slug_value>/", views.PostDetailView.as_view(), name="post-detail"),
    path("post/<slug:slug_value>/edit/", views.PostUpdateView.as_view(), name="post-update"),
]

router = routers.SimpleRouter()
router.register(r"blog/api/blogs", views_api.BlogListCreateAPIView, basename="blogs")
router.register(r"blog/api/posts", views_api.PostListCreateAPIView, basename="posts")

urlpatterns += router.urls

opalblog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from django.views.static import serve

from rest_framework import routers



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    # only available in DEV, in PROD served via apache or ngix 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.dispatch import receiver
from django.shortcuts import reverse
from django.utils import timezone

from django.core.exceptions import ValidationError
from django.db.models.signals import pre_save, post_save
from django.utils.translation import gettext_lazy as _

from .utlis import slugify


User = get_user_model()


def validate_title(value):
    if len(value) <= 10:
        raise ValidationError(
            _("%(value)s must be larger than 10 characters"),
            params={"value": value},
        )


class Blog(models.Model):
    title = models.CharField(
        verbose_name="Blog Title", max_length=256, validators=[validate_title]
    )
    description = models.TextField(blank=True)

    slug = models.SlugField(max_length=64, unique=True, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name="blogs")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:blog-detail", args=[self.slug])


class Post(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.PROTECT, related_name="posts")

    title = models.CharField(
        verbose_name="Post Title", max_length=256, validators=[validate_title]
    )
    content = models.TextField(blank=True)

    slug = models.SlugField(max_length=64, editable=False, null=True, blank=True)

    created_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name="posts")
    created_at = models.DateTimeField(auto_now_add=True)

    modified_at = models.DateTimeField(auto_now=True)

    published = models.BooleanField(verbose_name="Is Published", default=False)
    published_at = models.DateTimeField(
        verbose_name="Published at", null=True, blank=True
    )

    @property
    def author(self):
        return self.created_by

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post-detail", args=[self.slug])


@receiver(pre_save, sender=Blog)
def blog_pre_save(sender, instance, *args, **kwargs):
    instance.slug = slugify(sender, instance.title)


@receiver(pre_save, sender=Post)
def post_pre_save(sender, instance, *args, **kwargs):
    # slugify the title
    instance.slug = slugify(sender, instance.title)


@receiver(post_save, sender=Post)
def post_post_save(sender, instance, created, *args, **kwargs):
    # If published and no publication time, set to now
    if instance.published and not instance.published_at:
        instance.published_at = timezone.now()

blog/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from rest_framework import status

from .models import Blog, Post


class JsonableResponseMixin:
    """
    Mixin to add JSON support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """
    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.accepts('text/html'):
            return response
        else:
            return JsonResponse(form.errors, status=status.HTTP_401_UNAUTHORIZED)

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super().form_valid(form)
        if self.request.accepts('text/html'):
            return response
        else:
            data = {
                'pk': self.object.pk,
            }
            return JsonResponse(data)

class BlogDetailView(generic.ListView):
    slug_url_kwarg = "slug_value"
    slug_field = "slug"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            posts = Post.objects.filter(blog__slug=self.kwargs['slug_value'])
        else:
            posts = Post.objects.filter(blog__slug=self.kwargs['slug_value'], published=True)
        return posts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["blog"] = Blog.objects.filter(slug=self.kwargs['slug_value']).first()
        return context

class BlogCreateView(generic.CreateView):
    model = Blog
    fields = ['title', 'description']

    def form_valid(self, form):
        blog = form.save(commit=False)
        form.instance.created_by = self.request.user
        blog.save()
        return super(BlogCreateView, self).form_valid(form)

class BlogUpdateView(generic.UpdateView):
    model = Blog
    fields = ['title', 'description']
    slug_url_kwarg = "slug_value"
    slug_field = "slug"

class BlogListView(generic.ListView):

    def get_queryset(self):
        return Blog.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class PostCreateView(generic.CreateView):
    model = Post
    fields = ['title', 'content']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["blog"] = Blog.objects.filter(slug=self.kwargs['slug_value']).first()
        return context

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.created_by = self.request.user
        else:
            return super(PostCreateView, self).form_invalid(form)
        
        # fetch the current blog and update
        blog = Blog.objects.filter(slug=self.kwargs['slug_value']).first()
        post = form.save(commit=False)
        post.blog = blog
        post.save()
        return super(PostCreateView, self).form_valid(form)

class PostUpdateView(JsonableResponseMixin, generic.UpdateView):
    model = Post
    fields = ['title', 'content']
    slug_url_kwarg = "slug_value"
    slug_field = "slug"
    template_name = 'blog/post_update.html'

    def form_valid(self, form):
        if not (self.request.user.is_authenticated and self.request.user == self.get_object().created_by):
            form.errors['message'] = "User not authorized"
            form.errors['status'] = status.HTTP_401_UNAUTHORIZED
            return super(PostUpdateView, self).form_invalid(form)
        
        # fetch the current post and update
        return super(PostUpdateView, self).form_valid(form)

class PostDetailView(generic.DetailView):
    slug_url_kwarg = "slug_value"
    slug_field = "slug"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            posts = Post.objects.filter(slug=self.kwargs['slug_value'])
        else:
            posts = Post.objects.filter(slug=self.kwargs['slug_value'], published=True)
        return posts

blog/templates/blog/blog_form.html
{% extends "base_generic.html" %}

{% block content %}
<h2>New Blog</h2>
<form method="POST" enctype="multipart/form-data">
    <!-- Security token -->
    {% csrf_token %}
    <!-- Using the formset -->
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

blog/templates/blog/blog_list.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog.css' %}">
{% endblock %}

{% block content %}
  <h1>Blog list</h1>
  {% if blog_list %}
  <figure>
    <table>
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Blog Title</th>
        <th scope="col">Description</th>
        <th scope="col">Created By</th>
        <th scope="col">Created At</th>
        {% if user.is_authenticated %}
        <th scope="col">Action</th>
        {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for blog in blog_list %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a></td>
            <td>{{ blog.description }}</td>
            <td>{{ blog.created_by }}</td>
            <td>{{ blog.created_at }}</td>
            {% if user.is_authenticated %}
            <td><a href="{% url 'blog:blog-update' slug_value=blog.slug %}" role="button">Edit</a></td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
    </table>
</figure>
  <ul>
  </ul>
  {% else %}
    <p>There are no blogs.</p>
  {% endif %}
  {% if user.is_authenticated %}
  <a href="{% url 'blog:blog-create' %}" class="float">New</a>
  {% endif %}
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base_generic.html" %}
{% load markdown_extras %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p>Created by: {{ post.created_by }} | Created {{ post.created_at|timesince }} ago</p>
    {% if user.is_authenticated %}
        <a href="{% url 'blog:post-update' slug_value=post.slug %}" class="float">Edit</a>
    {% endif %}
    <p>{{ post.content | markdown | safe }}</p>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog.css' %}">
{% endblock %}

{% block content %}
<form enctype="multipart/form-data">
    <!-- Security token -->
    {% csrf_token %}
    <!-- Using the formset -->
    {{ form.as_p }}
    <input type="submit" value="Publish" id="publish">
    <input type="submit" value="Save as draft" id="draft">
</form>
<div id="snackbar">Success!</div>
{% endblock content %}
{% block script %}
function _(e){
    return document.getElementById(e);
};

function snack_success(message) {
    var snackbar = _("snackbar");
    snackbar.className = "show";
    setTimeout(function(){ snackbar.className = snackbar.className.replace("show", ""); }, 3000);
    setTimeout(function(){history.back();}, 3000);
}

function snack_error(message) {
    var snackbar = _("snackbar");
    snackbar.innerHTML = message;
    snackbar.className = "show";
    setTimeout(function(){ snackbar.className = snackbar.className.replace("show", ""); }, 3000);
    setTimeout(function(){history.back();}, 3000);
}

function getCookie(name){
    var cookieValue = null;

    if(document.cookie){
        var cookies = document.cookie.split(';');
        for(var i = 0; i < cookies.length; i++){
            cookie = cookies[i].trim();
            if(cookie.substring(0, name.length + 1) == (name + '=')){
                cookieValue = decodeURIComponent(cookie.substring(name.length+1));
                break;
            };
        };
    };
    return cookieValue;
};

var btn_draft = _('draft');
var btn_pub = _('publish');

btn_pub.addEventListener('click', function(e) {
    e.preventDefault();
    var title = _('id_title').value;
    var content = _('id_content').value;
    var csrfCookie = getCookie('csrftoken');

    const data = new FormData();
    data.append('title', title);
    data.append('content', content);
    data.append('published', true);
    data.append('csrfmiddlewaretoken', getCookie('csrftoken'));

    fetch("{% url 'blog:post-create' slug_value=blog.slug %}", {
        method: 'POST',
        body: data,
        credentials: 'same-origin',
    })
    .then(response => {
        console.log('Success:', data);
    })
    .catch((error) => {
        console.error('Error:', error);
    }); {
        headers: {
            'Accept': 'application/json',
        },
        method: 'POST',
        body: data,
        credentials: 'same-origin',
    }).then(async response => {
        const isJson = response.headers.get('content-type')?.includes('application/json');
        const data = isJson ? await response.json() : null;

        // check for error response
        if (!response.ok) {
            // get error message from body or default to response status
            const error = (data && data.message) || response.status;
            return Promise.reject(error);
        }
    }).then(datum => {
        console.log('Success:', datum);
        snack_success("Successful!");
    }).catch(error => {
        console.error('Error:', error);
        snack_error("Error: " + error);
    });
});

btn_draft.addEventListener('click', function(e){
    e.preventDefault();
    var title = _('id_title').value;
    var content = _('id_content').value;
    var csrfCookie = getCookie('csrftoken');

    const data = new FormData();
    data.append('title', title);
    data.append('content', content);
    data.append('csrfmiddlewaretoken', getCookie('csrftoken'));

    fetch("{% url 'blog:post-create' slug_value=blog.slug %}",  {
        headers: {
            'Accept': 'application/json',
        },
        method: 'POST',
        body: data,
        credentials: 'same-origin',
    }).then(async response => {
        const isJson = response.headers.get('content-type')?.includes('application/json');
        const data = isJson ? await response.json() : null;

        // check for error response
        if (!response.ok) {
            // get error message from body or default to response status
            const error = (data && data.message) || response.status;
            return Promise.reject(error);
        }
    }).then(datum => {
        console.log('Success:', datum);
        snack_success("Successful!");
    }).catch(error => {
        console.error('Error:', error);
        snack_error("Error: " + error);
    });
})
{% endblock %}

blog/templates/blog/post_list.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog.css' %}">
{% endblock %}

{% block content %}
{% if blog %}
    <h1>{{ blog.title }}</h1>
    <p>{{ blog.description }} | Created by: {{ blog.created_by }} | Created {{ blog.created_at|timesince }} ago</p>
    {% if post_list %}
        <div class="blogs-container">
        {% for post in post_list %}
        <div class="blog-card">
            <div class="blog-content">
            <h3 class="blog-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
            <div class="blog-topic">
                <a href="{{ post.get_absolute_url }}" class="btn btn-primary">{{post.content|slice:":200" }}...
                </br>
                Read More &rarr;</a>
            </div>
            <div class="blog-footer"> {{ post.created_by }} | {% if post.published %} {{post.published_at|timesince }} {% else %} Unpublished {% endif %}</div>
            </div>
        </div>
        {% endfor %}
        </div>
    {% else %}
        <p>There are no posts.</p>
    {% endif %}
    {% if user.is_authenticated %}
        <a href="{% url 'blog:post-create' slug_value=blog.slug %}" class="float">New</a>
    {% endif %}
{% endif %}
{% endblock %}

blog/templates/blog/post_update.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog.css' %}">
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<form enctype="multipart/form-data">
    <!-- Security token -->
    {% csrf_token %}
    <!-- Using the formset -->
    <p>
    <label for="id_title">Post Title:</label>
    <input type="text" name="title" maxlength="256" required id="id_title" value="{{post.title}}">
    </p>
    <p>
    <label for="id_content">Content:</label>
    <textarea name="content" cols="40" rows="10" id="id_content">
        {{post.content}}
    </textarea>
    </p>
    <input type="submit" value="Publish" id="publish">
    <input type="submit" value="Save as draft" id="draft">
</form>
<div id="snackbar">Success!</div>
{% else %}
    <h1>{{ post.title }}</h1>
    <p>Created by: {{ post.created_by }} | Created {{ post.created_at|timesince }} ago</p>
    <p>{{ post.content }}</p>
{% endif %}
{% endblock %}

{% block script %}
function _(e){
    return document.getElementById(e);
};

function snack_success(message) {
    var snackbar = _("snackbar");
    snackbar.className = "show";
    setTimeout(function(){ snackbar.className = snackbar.className.replace("show", ""); }, 3000);
    setTimeout(function(){history.back();}, 3000);
}

function snack_error(message) {
    var snackbar = _("snackbar");
    snackbar.innerHTML = message;
    snackbar.className = "show";
    setTimeout(function(){ snackbar.className = snackbar.className.replace("show", ""); }, 3000);
    setTimeout(function(){history.back();}, 3000);
}

function getCookie(name){
    var cookieValue = null;

    if(document.cookie){
        var cookies = document.cookie.split(';');
        for(var i = 0; i < cookies.length; i++){
            cookie = cookies[i].trim();
            if(cookie.substring(0, name.length + 1) == (name + '=')){
                cookieValue = decodeURIComponent(cookie.substring(name.length+1));
                break;
            };
        };
    };
    return cookieValue;
};

var btn_draft = _('draft');
var btn_pub = _('publish');

btn_pub.addEventListener('click', function(e) {
    e.preventDefault();
    var title = _('id_title').value;
    var content = _('id_content').value;
    var csrfCookie = getCookie('csrftoken');

    const data = new FormData();
    data.append('title', title);
    data.append('content', content);
    data.append('published', true);
    data.append('csrfmiddlewaretoken', getCookie('csrftoken'));

    fetch("{% url 'blog:post-update' slug_value=post.slug %}", {
        headers: {
            'Accept': 'application/json',
        },
        method: 'POST',
        body: data,
        credentials: 'same-origin',
    }).then(async response => {
        const isJson = response.headers.get('content-type')?.includes('application/json');
        const data = isJson ? await response.json() : null;

        // check for error response
        if (!response.ok) {
            // get error message from body or default to response status
            const error = (data && data.message) || response.status;
            return Promise.reject(error);
        }
    }).then(datum => {
        console.log('Success:', datum);
        snack_success("Successful!");
    }).catch(error => {
        console.error('Error:', error);
        snack_error("Error: " + error);
    });
});

btn_draft.addEventListener('click', function(e){
    e.preventDefault();
    var title = _('id_title').value;
    var content = _('id_content').value;
    var csrfCookie = getCookie('csrftoken');

    const data = new FormData();
    data.append('title', title);
    data.append('content', content);
    data.append('csrfmiddlewaretoken', getCookie('csrftoken'));

    fetch("{% url 'blog:post-update' slug_value=post.slug %}", {
        headers: {
            'Accept': 'application/json',
        },
        method: 'POST',
        body: data,
        credentials: 'same-origin',
    }).then(async response => {
        const isJson = response.headers.get('content-type')?.includes('application/json');
        const data = isJson ? await response.json() : null;

        // check for error response
        if (!response.ok) {
            // get error message from body or default to response status
            const error = (data && data.message) || response.status;
            return Promise.reject(error);
        }
    }).then(datum => {
        console.log('Success:', datum);
        snack_success("Successful!");
    }).catch(error => {
        console.error('Error:', error);
        snack_error("Error: " + error);
    });
  });
{% endblock %}